# Generated by Django 5.1.4 on 2025-03-30 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioweb', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BasicInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('designation', models.TextField()),
                ('about', models.TextField()),
                ('profile_picture', models.ImageField(upload_to='uploads/profile_picture/%y/%m/%d')),
            ],
            options={
                'verbose_name_plural': 'BasicInfo',
            },
        ),
        migrations.AlterModelOptions(
            name='procategory',
            options={'verbose_name_plural': 'proCategories'},
        ),
        migrations.AlterModelOptions(
            name='projects',
            options={'verbose_name_plural': 'Projects'},
        ),
    ]
