# Generated by Django 5.1.4 on 2025-03-30 11:22

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioweb', '0002_basicinfo_alter_procategory_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basicinfo',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
