# Generated by Django 5.1.4 on 2025-03-30 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioweb', '0003_alter_basicinfo_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basicinfo',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
