# Generated by Django 5.1.4 on 2025-03-30 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioweb', '0004_alter_basicinfo_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='basicinfo',
            options={'verbose_name_plural': 'Basic Info'},
        ),
        migrations.AddField(
            model_name='basicinfo',
            name='resume_link',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='basicinfo',
            name='designation',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='basicinfo',
            name='name',
            field=models.CharField(default='Muniraju B R', editable=False, max_length=100),
        ),
    ]
