# Generated by Django 5.1.4 on 2025-03-30 14:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioweb', '0005_alter_basicinfo_options_basicinfo_resume_link_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='achiveCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('achiveCat_name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name_plural': 'achiveCategory',
            },
        ),
        migrations.AddField(
            model_name='projects',
            name='project_link',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.CreateModel(
            name='Achievements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
                ('thumbnail_image', models.ImageField(upload_to='uploads/%y/%m/%d')),
                ('status', models.CharField(choices=[('ongoing', 'Ongoing'), ('completed', 'Completed')], default='ongoing', max_length=100)),
                ('completed_date', models.DateField(blank=True, null=True)),
                ('credit_link', models.URLField(blank=True, max_length=500)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='portfolioweb.achivecategory')),
            ],
            options={
                'verbose_name_plural': 'Projects',
            },
        ),
    ]
