# Generated by Django 5.1.4 on 2025-03-30 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioweb', '0006_achivecategory_projects_project_link_achievements'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='achievements',
            options={'verbose_name_plural': 'Achievements'},
        ),
    ]
