# Generated by Django 5.1.4 on 2025-04-22 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioweb', '0008_education_skillcategory_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='basicinfo',
            name='external_link',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='basicinfo',
            name='external_logo',
            field=models.URLField(blank=True, null=True),
        ),
    ]
