# Generated by Django 5.1.4 on 2025-04-22 12:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioweb', '0009_basicinfo_external_link_basicinfo_external_logo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basicinfo',
            name='external_link',
        ),
        migrations.RemoveField(
            model_name='basicinfo',
            name='external_logo',
        ),
        migrations.CreateModel(
            name='ExternalLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('url', models.URLField()),
                ('logo_url', models.URLField(blank=True, null=True)),
                ('basic_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='external_links', to='portfolioweb.basicinfo')),
            ],
        ),
    ]
