# Generated by Django 5.1.4 on 2025-04-22 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioweb', '0010_remove_basicinfo_external_link_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='externallink',
            name='logo_url',
        ),
        migrations.AddField(
            model_name='externallink',
            name='icon_class',
            field=models.CharField(blank=True, help_text='Font Awesome class (e.g., "fab fa-github")', max_length=100, null=True),
        ),
    ]
