# Generated by Django 5.1.4 on 2025-04-22 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioweb', '0011_remove_externallink_logo_url_externallink_icon_class'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ExternalLink',
        ),
    ]
