# Generated by Django 5.1.4 on 2025-04-24 08:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioweb', '0012_delete_externallink'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('url', models.URLField()),
                ('icon_class', models.CharField(blank=True, help_text='Font Awesome class (e.g., "fab fa-github")', max_length=100, null=True)),
                ('basic_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='external_links', to='portfolioweb.basicinfo')),
            ],
        ),
    ]
