# Generated by Django 5.1.4 on 2025-04-25 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioweb', '0013_externallink'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='externallink',
            name='icon_class',
        ),
    ]
